# Generated by Django 2.2.16 on 2023-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230215_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Укажите дату', verbose_name='Дата комментария'),
        ),
    ]
